version: '3.9'

services:
  postgres:
    image: postgres:14.1-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=courseworkDB
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    container_name: coursework_spring
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/courseworkDB
      - SPRING_DATASOURCE_USERNAME=db_user
      - SPRING_DATASOURCE_PASSWORD=db_pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8081:8081'
    depends_on:
      postgres:
        condition: service_healthy
#  react:
#    container_name: coursework_react
#    build: ../post_service_frontend
#    ports:
#      - "3000:3000"
#    restart: always
#    volumes:
#      - ../post_service_frontend/src:/src/app/src
#    links:
#      - postgres
#      - app